### ISSUE TITLE
Add dependabot

### ISSUE THREAD

**Issue by JoeNg93** [JoeNg93/vtqh-blog#1]
## Context

To keep the dependencies up to date.

## Resources

1. https://docs.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically

**Comment by JoeNg93** [comment]
Example config:

```
---
# See: https://dependabot.com/docs/config-file/
version: 1
update_configs:
  # Dependabot will detect the lerna mono-repo and discover packages in there
  - directory: /
    package_manager: javascript
    update_schedule: live
    version_requirement_updates: increase_versions
    ignored_updates:
      - match:
          dependency_name: "jsii*"
      - match:
          dependency_name: "@jsii/*"
      - match:
          dependency_name: "codemaker"
      - match:
          dependency_name: "@types/node"
          version_requirement: ">=11.0.0-0"
```
